server:
  port : 8081

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: myGroup
    auto-offset-reset: earliest
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer